name: flutter_intl
description: "another internationalization library"
version: 0.0.4+1
homepage: https://github.com/Anfet/flutter_intl.git

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  assets:
    - assets/
    - assets/intl/